language: c
compiler: gcc
matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD='make -C lib all && CFLAGS="-O1 -g" make -C zlibWrapper valgrindTest'
      addons:
        apt:
          packages:
            - valgrind
    - os: linux
      dist: trusty
      sudo: required
      env: PLATFORM="Ubuntu 14.04" CMD="make zlibwrapper"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - gcc-5
            - gcc-5-multilib
            - gcc-6
            - gcc-6-multilib
  exclude:
    - compiler: gcc

script:
  - sh -c "$CMD"
