language: c

before_install:
  - "wget https://launchpad.net/ubuntu/+source/cmake/2.8.8-2ubuntu1/+build/3441442/+files/cmake_2.8.8-2ubuntu1_amd64.deb"
  - "wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake-data_2.8.8-2ubuntu1_all.deb"
  - "sudo apt-get remove cmake-data cmake"
  - sudo apt-get update  -qq
  - sudo apt-get install -qq gcc-arm-linux-gnueabi
  - sudo apt-get install -qq clang
  - sudo apt-get install -qq g++-multilib
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq valgrind

install:
    - "sudo dpkg --install cmake-data_2.8.8-2ubuntu1_all.deb cmake_2.8.8-2ubuntu1_amd64.deb" 

env:
  - ZSTD_TRAVIS_CI_ENV=travis-install
  - ZSTD_TRAVIS_CI_ENV=cmaketest
  - ZSTD_TRAVIS_CI_ENV=clangtest  
  - ZSTD_TRAVIS_CI_ENV=gpptest  
  - ZSTD_TRAVIS_CI_ENV=armtest  
  - ZSTD_TRAVIS_CI_ENV=test  
  - ZSTD_TRAVIS_CI_ENV="-C programs test32"  
  - ZSTD_TRAVIS_CI_ENV="-C programs test-zstd_nolegacy"
  - ZSTD_TRAVIS_CI_ENV=usan
  - ZSTD_TRAVIS_CI_ENV=asan
  - ZSTD_TRAVIS_CI_ENV=asan32
  - ZSTD_TRAVIS_CI_ENV="-C programs valgrindTest"  
  
compiler: gcc

script: 
  - make $ZSTD_TRAVIS_CI_ENV

matrix:
  fast_finish: true