language: c
sudo: required
dist: trusty
matrix:
  fast_finish: true
  include:
    # OS X Mavericks
    - env: Ubu=OS_X_Mavericks Cmd="make gnu90test && make clean && make test && make clean && make travis-install"
      os: osx

    # Ubuntu 14.04 LTS Server Edition 64 bit
    - env: Ubu=14.04 Cmd='make gpp6install uasan-test && cd contrib/pzstd && make test-pzstd && make test-pzstd32 && make test-pzstd-tsan && make test-pzstd-asan'
      install:
        - export CXX="g++-6" CC="gcc-6"
    - env: Ubu=14.04 Cmd='CC=gcc-6 make gcc6install uasan-test32 && make clean zlibwrapper && make -C tests clean test-zstd-nolegacy && make -C tests versionsTest'
    - env: Ubu=14.04 Cmd="make arminstall armtest && make clean && make aarch64test"
    - env: Ubu=14.04 Cmd='make ppcinstall ppctest && make clean && make ppc64test'

    # other feature branches => short tests
    - env: Ubu=14.04 Cmd='make valgrindinstall lib && CFLAGS="-O1 -g" make -C zlibWrapper valgrindTest && make -C tests valgrindTest'
    - env: Ubu=14.04 Cmd="make libc6install && make -C tests test32"

script:
  - JOB_NUMBER=$(echo $TRAVIS_JOB_NUMBER | sed -e 's:[0-9][0-9]*\.\(.*\):\1:')
  #  cron & master          => long tests, as this is the final step towards a Release
  #  dev && pull requests   => normal tests
  #  other feature branches => short tests (number > 5)
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ] || [ "$TRAVIS_BRANCH" = "master" ]; then
        FUZZERTEST=-T7mn sh -c "$Cmd" || travis_terminate 1;
    else
        if [ "$TRAVIS_PULL_REQUEST" = "true" ] || [ $JOB_NUMBER -gt 5 ] || [ "$TRAVIS_BRANCH" = "dev" ]; then
            sh -c "$Cmd" || travis_terminate 1;
        fi
    fi
