language: c

before_install:
  - "wget -q http://cardinot.net/files/cmake-2.8.11.tar.gz"
  - "tar -xzvf cmake-2.8.11.tar.gz"
  - sudo apt-get update  -qq
  - sudo apt-get install -qq gcc-arm-linux-gnueabi
  - sudo apt-get install -qq clang
  - sudo apt-get install -qq g++-multilib
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq valgrind

install:
  - "cd cmake-2.8.11"
  - "./bootstrap --prefix=/usr --system-libs --mandir=/share/man"
  - "make -j 16"
  - "sudo make install -j 16"
  - "cd .."

env:
  - ZSTD_TRAVIS_CI_ENV=travis-install
  - ZSTD_TRAVIS_CI_ENV=cmaketest
  - ZSTD_TRAVIS_CI_ENV=clangtest  
  - ZSTD_TRAVIS_CI_ENV=gpptest  
  - ZSTD_TRAVIS_CI_ENV=armtest  
  - ZSTD_TRAVIS_CI_ENV=test  
  - ZSTD_TRAVIS_CI_ENV="-C programs test32"  
  - ZSTD_TRAVIS_CI_ENV="-C programs test-zstd_nolegacy"
  - ZSTD_TRAVIS_CI_ENV=usan
  - ZSTD_TRAVIS_CI_ENV=asan
  - ZSTD_TRAVIS_CI_ENV=asan32
  - ZSTD_TRAVIS_CI_ENV="-C programs valgrindTest"  
  
compiler: gcc

script: 
  - make $ZSTD_TRAVIS_CI_ENV

matrix:
  fast_finish: true
