version: 1.0.{build}
configuration:
- Release
- Debug
platform:
- Win32
- x64

build_script:
- cmd: |
    ECHO ***
    ECHO *** Building Visual Studio 2008 %PLATFORM%\%CONFIGURATION%
    ECHO ***
    msbuild "projects\VS2008\zstd.sln" /m /verbosity:minimal /property:PlatformToolset=v90 /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    COPY projects\VS2008\bin\%PLATFORM%\%CONFIGURATION%\fuzzer.exe projects\fuzzer_VS2008_%PLATFORM%_%CONFIGURATION%.exe

    ECHO ***
    ECHO *** Building Visual Studio 2010 %PLATFORM%\%CONFIGURATION%
    ECHO ***
    REM msbuild "projects\VS2010\zstd.sln" /m /verbosity:detailed /property:PlatformToolset=Windows7.1SDK /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    REM msbuild "projects\VS2010\zstd.sln" "/p:AdditionalLibPaths=C:\Program Files\Microsoft SDKs\Windows\v7.1\Lib\X64" /m /verbosity:detailed /property:PlatformToolset=v100 /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    msbuild "projects\VS2010\zstd.sln" /p:LibraryPath="C:\Program Files\Microsoft SDKs\Windows\v7.1\lib\x64;c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 10.0\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\lib\amd64;" /m /verbosity:normal /property:PlatformToolset=v100 /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    COPY projects\VS2010\bin\%PLATFORM%\%CONFIGURATION%\fuzzer.exe projects\fuzzer_VS2010_%PLATFORM%_%CONFIGURATION%.exe

    ECHO ***
    ECHO *** Building Visual Studio 2012 %PLATFORM%\%CONFIGURATION%
    ECHO ***
    msbuild "projects\VS2010\zstd.sln" /m /verbosity:minimal /property:PlatformToolset=v110 /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    COPY projects\VS2010\bin\%PLATFORM%\%CONFIGURATION%\fuzzer.exe projects\fuzzer_VS2012_%PLATFORM%_%CONFIGURATION%.exe

    ECHO ***
    ECHO *** Building Visual Studio 2013 %PLATFORM%\%CONFIGURATION%
    ECHO ***
    msbuild "projects\VS2010\zstd.sln" /m /verbosity:minimal /property:PlatformToolset=v120 /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    COPY projects\VS2010\bin\%PLATFORM%\%CONFIGURATION%\fuzzer.exe projects\fuzzer_VS2013_%PLATFORM%_%CONFIGURATION%.exe

    ECHO ***
    ECHO *** Building Visual Studio 2015 %PLATFORM%\%CONFIGURATION%
    ECHO ***
    msbuild "projects\VS2010\zstd.sln" /m /verbosity:normal /property:PlatformToolset=v140 /t:Clean,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    COPY projects\VS2010\bin\%PLATFORM%\%CONFIGURATION%\fuzzer.exe projects\fuzzer_VS2015_%PLATFORM%_%CONFIGURATION%.exe

test_script:
- cmd: SET FUZZERTEST=-T1mn
- cmd: |
    IF %CONFIGURATION%==Release (projects\fuzzer_VS2008_%PLATFORM%_Release.exe %FUZZERTEST%)
    IF %CONFIGURATION%==Release (projects\fuzzer_VS2010_%PLATFORM%_Release.exe %FUZZERTEST%)
    IF %CONFIGURATION%==Release (projects\fuzzer_VS2012_%PLATFORM%_Release.exe %FUZZERTEST%)
    IF %CONFIGURATION%==Release (projects\fuzzer_VS2013_%PLATFORM%_Release.exe %FUZZERTEST%)
    IF %CONFIGURATION%==Release (projects\fuzzer_VS2015_%PLATFORM%_Release.exe %FUZZERTEST%)
